// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQXxlMgCvLbKas0i9C1mYUrQ6fKBBoU9k',
    appId: '1:826146207329:web:6de0c8604d0557e08ddc20',
    messagingSenderId: '826146207329',
    projectId: 'hrms-54901',
    authDomain: 'hrms-54901.firebaseapp.com',
    storageBucket: 'hrms-54901.firebasestorage.app',
    measurementId: 'G-YGE0ZY9VJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8a1bm9znQWgIqvxM1i0ZveF57bchU-RA',
    appId: '1:826146207329:android:ba9025036e02e8878ddc20',
    messagingSenderId: '826146207329',
    projectId: 'hrms-54901',
    storageBucket: 'hrms-54901.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7mUQ1seaKT4xKS_3vD4y-pg-z-AZbieg',
    appId: '1:826146207329:ios:936d615a380fc7038ddc20',
    messagingSenderId: '826146207329',
    projectId: 'hrms-54901',
    storageBucket: 'hrms-54901.firebasestorage.app',
    iosBundleId: 'com.example.hrms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7mUQ1seaKT4xKS_3vD4y-pg-z-AZbieg',
    appId: '1:826146207329:ios:936d615a380fc7038ddc20',
    messagingSenderId: '826146207329',
    projectId: 'hrms-54901',
    storageBucket: 'hrms-54901.firebasestorage.app',
    iosBundleId: 'com.example.hrms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQXxlMgCvLbKas0i9C1mYUrQ6fKBBoU9k',
    appId: '1:826146207329:web:4e4c1267c2e6e0c88ddc20',
    messagingSenderId: '826146207329',
    projectId: 'hrms-54901',
    authDomain: 'hrms-54901.firebaseapp.com',
    storageBucket: 'hrms-54901.firebasestorage.app',
    measurementId: 'G-L4QMS39C7V',
  );

}